import torch
from src.examples.tensor_field_networks.nonlinearity_layer import TfnNonlinearityLayer
from src.examples.tensor_field_networks.point_convolution_layer import PointConvolutionLayer
from src.examples.tensor_field_networks.self_interaction_layer import SelfInteractionLayer
from src.examples.tensor_field_networks.tfn_utils import createGraphData