from typing import List
import re
import sys

"""
This file takes in a list containing all PyTorch operations, and generates a
base class which can be used in a SFINAE-type style to call all pytorch
operations for any give class on its instance variables.
"""

def getData(file : str, prefix = "Tensor") -> List[str]:
  Lines = file.readlines()
  
  # Strips the newline character
  non_empty_lines = []
  for line in Lines:
      line = line.strip()
      if line != "":
         non_empty_lines.append(line)

  functions = []
  regex = "^{0}[.](.*)$".format(prefix)
  for line in non_empty_lines:
    regex_result = re.search(regex, line)
    if regex_result == None:
       continue
    
    function = regex_result.group(1)
    functions.append(function)

  return functions

def writeFunction(f, function_name : str):
  function = """
    def {0}(self, *args, **kwargs):
      results = []
      parts = self.__getParts()

      # Calculate the result for each individual part.
      for i in range(len(parts)):
        part = parts[i]

        # Modify all |args| that are PointCloud instances to just be the
        # specific part we care about.
        part_args = list(args)
        for i, arg in enumerate(args):
          if isinstance(arg, self.__child_type):
            part_args[i] = arg.__getParts()[i]
          elif isinstance(arg, torch.Tensor):
            assert arg.size()[-2] == 1
            new_size = list(arg.size())
            new_size[-2] = part.size()[-2]
            part_args[i] = arg.expand(tuple(new_size))

        # Do the same for |kwargs|.
        part_kwargs = kwargs.copy()
        for key, value in kwargs.items():
          if isinstance(value, self.__child_type):
            part_kwargs[key] = value.__getParts()[i]
          elif isinstance(value, torch.Tensor):
            assert value.size()[-2] == 1
            new_size = list(value.size())
            new_size[-2] = part.size()[-2]
            part_kwargs[key] = arg.expand(tuple(new_size))

        # Call the underlying function with modifies parameters.
        results.append(part.{0}(*part_args, **part_kwargs))

      # Turn it into an object and return it
      return self.__createObject(results)
  """
  f.write(function.format(function_name))

def writeHeader(f):
  str = """from typing import List

import torch

class TensorRecurser:
  \"""
   To use this class, the child must define the following functions:
   1. self.getParts() to return the tensor-like objects to iterate over.
   2. self.createObject(results) to create a new instance of the object to be
      returned to the caller.

   NOTE: This file is autogenerated programmatically. Do not make manual changes
   as they won't persist.
  \"""

  def __init__(self, child_type, *args, **kwargs):
    \"""
    |child_type| is the type of the child that extends this parent, to allow
    this class to act in a SFINAE manner.
    \"""
    self.__child_type = child_type

"""

  f.write(str)

if __name__=="__main__": 
    command_args = sys.argv
    assert len(command_args) == 3, len(command_args)

    source = command_args[1]
    dest = command_args[2]

    print("Source:", source, " Dest:", dest)

    source = open(source, "r")
    dest = open(dest, "x")  # TODO: w not x

    functions = getData(source)

    writeHeader(dest)
    for func in functions:
       writeFunction(dest, func)
